debug: true


server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.0.223/withus2?serverTimezone=Asia/Seoul
    username: withus2
    password: withus2
  jpa:
    show-sql: false
  profiles: local