server:
  port: 80
  shutdown: graceful

spring:
  application.name: withus
  task:
    execution:
      pool:
        max-size: 20
        core-size: 10
      thread-name-prefix: TNP-
  datasource:
    url: jdbc:mysql://127.0.0.1/withus?serverTimezone=Asia/Seoul
    username: withus
    password: Withus@12
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: true
    open-in-view: false

    # If you use a logging framework like log4j,
    # you should always set that property to false
    # because it gives you no benefit at all.
    # https://stackoverflow.com/a/22977693/1986241
    show-sql: true

    hibernate:
      # ex) ddl-auto: none, create-drop, create, update, validate
      ddl-auto: validate