server:
  port: 8080
  shutdown: graceful

spring:
  application.name: withus

  datasource:
    url: jdbc:mysql://110.4.83.23/withus?serverTimezone=Asia/Seoul
    username: withus
    password: Withus@12
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: true
    open-in-view: false

    # If you use a logging framework like log4j,
    # you should always set that property to false
    # because it gives you no benefit at all.
    # https://stackoverflow.com/a/22977693/1986241
    show-sql: true

    hibernate:
      # ex) ddl-auto: none, create-drop, create, update, validate
      ddl-auto: validate