server:
  port: 8080
  shutdown: graceful

spring:
  application.name: withus1

  datasource:
    url: jdbc:mysql://192.168.0.223/withus2?serverTimezone=Asia/Seoul
    username: withus2
    password: withus2
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: true
    open-in-view: false

    # If you use a logging framework like log4j,
    # you should always set that property to false
    # because it gives you no benefit at all.
    # https://stackoverflow.com/a/22977693/1986241
    show-sql: false
    hibernate:
      ddl-auto: update