server:
  port: 80
  shutdown: graceful

spring:
  application.name: Withus
  datasource:
    url: jdbc:mysql://192.168.0.223/withus?serverTimezone=Asia/Seoul
    username: withus
    password: withus
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
